package application.model;
// Generated Mar 11, 2017 10:05:54 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Calendar;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookLoans generated by hbm2java
 */
@Entity
@Table(name = "book_loans", catalog = "library")
public class BookLoans implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -8953113318106535058L;
	private Integer loanId;
	private Book book;
	private Borrower borrower;
	private Calendar dateOut;
	private Calendar dueDate;
	private Calendar datein;
	private Fines fines;

	public BookLoans() {
	}

	public BookLoans(Book book, Borrower borrower, Calendar dateOut, Calendar dueDate, Calendar datein,
			Fines fines) {
		this.book = book;
		this.borrower = borrower;
		this.dateOut = dateOut;
		this.dueDate = dueDate;
		this.datein = datein;
		this.fines = fines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Loan_id", unique = true, nullable = false)
	public Integer getLoanId() {
		return this.loanId;
	}

	public void setLoanId(Integer loanId) {
		this.loanId = loanId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Isbn")
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Card_id")
	public Borrower getBorrower() {
		return this.borrower;
	}

	public void setBorrower(Borrower borrower) {
		this.borrower = borrower;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date_out", length = 19, insertable = false, updatable = false)
	public Calendar getDateOut() {
		return this.dateOut;
	}

	public void setDateOut(Calendar dateOut) {
		this.dateOut = dateOut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Due_date", length = 19, insertable = false, updatable = false)
	public Calendar getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Calendar dueDate) {
		this.dueDate = dueDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Datein", length = 19)
	public Calendar getDatein() {
		return this.datein;
	}

	public void setDatein(Calendar datein) {
		this.datein = datein;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "bookLoans")
	public Fines getFines() {
		return this.fines;
	}

	public void setFines(Fines fines) {
		this.fines = fines;
	}

}
