package application.model;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "library")
public class Book implements java.io.Serializable {

	private static final long serialVersionUID = 63520014597626342L;
	private String isbn;
	private String title;
	private String cover;
	private String publisher;
	private Integer pages;
	private Integer availability;
	private Set<BookLoans> bookLoanses = new HashSet<>(0);
	private Set<Authors> authorses = new HashSet<>(0);

	public Book() {
	}

	public Book(String isbn) {
		this.isbn = isbn;
	}

	public Book(String isbn, String title, String cover, String publisher, Integer pages,Integer availability, Set<BookLoans> bookLoanses,
			Set<Authors> authorses) {
		this.isbn = isbn;
		this.title = title;
		this.cover = cover;
		this.publisher = publisher;
		this.pages = pages;
		this.availability = availability;
		this.bookLoanses = bookLoanses;
		this.authorses = authorses;
	}

	@Id

	@Column(name = "Isbn", unique = true, nullable = false, length = 10)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "Title", length = 300)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Cover", length = 400)
	public String getCover() {
		return this.cover;
	}

	public void setCover(String cover) {
		this.cover = cover;
	}

	@Column(name = "Publisher", length = 300)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "Pages")
	public Integer getPages() {
		return this.pages;
	}

	public void setPages(Integer pages) {
		this.pages = pages;
	}

	@Column(name = "Availability")
	public Integer getAvailability() {
		return this.availability;
	}

	public void setAvailability(Integer availability) {
		this.availability = availability;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<BookLoans> getBookLoanses() {
		return this.bookLoanses;
	}

	public void setBookLoanses(Set<BookLoans> bookLoanses) {
		this.bookLoanses = bookLoanses;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "books")
	public Set<Authors> getAuthorses() {
		return this.authorses;
	}

	public void setAuthorses(Set<Authors> authorses) {
		this.authorses = authorses;
	}

}
