package application.model;

// default package
// Generated Mar 11, 2017 10:05:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Borrower generated by hbm2java
 */
@Entity
@Table(name = "borrower", catalog = "library")
public class Borrower implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -5155969196836063514L;
	private Integer cardId;
	private String ssn;
	private String firstName;
	private String lastName;
	private String email;
	private String address;
	private String city;
	private String state;
	private String phone;
	private Set<BookLoans> bookLoanses = new HashSet<>(0);

	public Borrower() {
	}

	public Borrower(String ssn, String firstName, String lastName, String email, String address, String city,
			String state, String phone, Set<BookLoans> bookLoanses) {
		this.ssn = ssn;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.address = address;
		this.city = city;
		this.state = state;
		this.phone = phone;
		this.bookLoanses = bookLoanses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Card_id", unique = true, nullable = false)
	public Integer getCardId() {
		return this.cardId;
	}

	public void setCardId(Integer cardId) {
		this.cardId = cardId;
	}

	@Column(name = "SSN", length = 15)
	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	@Column(name = "FirstName", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LastName", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Email", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Address", length = 1000)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "City", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "borrower")
	public Set<BookLoans> getBookLoanses() {
		return this.bookLoanses;
	}

	public void setBookLoanses(Set<BookLoans> bookLoanses) {
		this.bookLoanses = bookLoanses;
	}

}
