package application.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Authors generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "library")
public class Users implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String userName;
	private String password;
	private Long role;

	public Users() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "User_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "Username", length = 200)
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password", length = 200)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Role", precision = 10, scale = 0)
	public Long getRole() {
		return role;
	}

	public void setRole(Long role) {
		this.role = role;
	}

}
